### ISSUE TITLE
Issues after moving HomeAssistant process into Docker

### ISSUE THREAD

**Issue by kf-nz** [aetolus/Home-AssistantConfig#1]
After commit: https://github.com/aetolus/Home-AssistantConfig/commit/95927bdc054b4c09272392659f5ce036433acb2e

### Issues
- ~~Command Line binary sensors for Ping don't work~~
-- Fixed after changing to use native ping binary sensor
- ~~SSH shell_commands don't work~~
-- Fixed after adding persistent storage to ~/.ssh and regenerating SSH keys
- ~~SSHPass shell_commands don't work~~
-- Copied SSHPass binary to persistent storage location

**Comment by kf-nz** [comment]
- `ERROR (MainThread) [homeassistant.core] Timer got out of sync. Resetting`
- ~~`ERROR (SyncWorker_0) [miio.device] Got error when receiving: timed out`~~
-- Fixed static IP/config clashes
- ~~input_select.harmony_activities not syncing state with Harmony Hub after HA restart~~
-- Fixed
- ~~Security camera motion won't work, need to connect /var/lib/motion to persistent storage for docker and adjust whitelist~~
-- Complete, additional error detailed below
- ~~Reboot host from Telegram won't work~~
-- Fixed, added ha_dockermon and changed to use rest_command to restart the HA container

**Comment by kf-nz** [comment]
- ~~Need to implement docker-compose to ensure containers start in correct order~~
-- Complete

**Comment by kf-nz** [comment]
- ~~Hue lights disappeared after container restart~~
-- Missed a breaking change update, required updating configuration.yaml

**Comment by kf-nz** [comment]
```
2018-03-15 11:29:31.777637 WARNING AppDaemon: ------------------------------------------------------------                                                       
2018-03-15 11:29:31.777953 WARNING AppDaemon: Unexpected error initializing app: security_motion:                                                                
2018-03-15 11:29:31.778192 WARNING AppDaemon: ------------------------------------------------------------                                                       
2018-03-15 11:29:31.779052 WARNING AppDaemon: Traceback (most recent call last):                                                                                 
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1953, in check_app_updates                                                          
    self.init_object(app)                                                                                                                                        
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1481, in init_object                                                                
    modname = __import__(app_args["module"])                                                                                                                     
  File "/conf/apps/security_motion.py", line 6, in <module>                                                                                                      
    from clarifai.rest import ClarifaiApp                                                                                                                        
ModuleNotFoundError: No module named 'clarifai' 
```

Need to have appdaemon install clarifai python module into docker container
-- Scratching this app for the time being, until additional cameras are in place
